### ISSUE TITLE
Remember page position/index 

### ISSUE THREAD

**Issue by d02d33pak** [Janglee123/eplee#1]
some way to open the book from where you left it, somehow it could remember the page number/position/index to the user can continue reading from where they left..? make sense? :thinking:

**Comment by Janglee123** [comment]
Thanks for the opening issue.
Yes, it is nice to have this feature. We can do that by storing [CFI](https://www.idpf.org/epub/linking/cfi/epub-cfi.html#sec-epubcfi-def) (it is like page number for epub) of the last page into a database. And restore it when a book opens.

**Comment by Janglee123** [comment]
If you don't mind join our discord server. https://discord.gg/57XchT

**Comment by Janglee123** [comment]
solved in master branch.
